### ISSUE TITLE
Template Repository

### ISSUE THREAD

**Issue by fahadasq** [DevM7mdAli/Q-Store#1]
Hello!

I just saw this repository, and as I understand, it's essentially a template repository for vscode java projects. If you're intention is to stream-line the creation of java workspaces for vscode, you can turn this into a template repository by going to the repository settings and enabling "Template repository." This way, if someone wants to use this template, they can simply click the "Use this template" button, which will basically clone this repository but under a new repository of their making. Plus, in that new repository, it will be visible that the repository was templated from this one, which would credit you for the template. It's much easier for users  this way plus it's better for you as the creator of this template. This is just a suggestion of course but I highly recommend doing it this way since it's beneficial for all :)

Of course I might be wrong, and this may not be a template repository at all. So in that case you can just ignore this suggestion.

**Comment by DevM7mdAli** [comment]
Hello Fahad, this is a repo for group project for subject OOP 2
